"""add unique constraint to recovery case payment id

Revision ID: bda6f6c8241e
Revises: 4b2a0a970873
Create Date: 2026-08-25 14:56:46.499653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda6f6c8241e'
down_revision: Union[str, Sequence[str], None] = '4b2a0a970873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_cases_payment_id'), table_name='recovery_cases')
    op.create_index(op.f('ix_recovery_cases_payment_id'), 'recovery_cases', ['payment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_cases_payment_id'), table_name='recovery_cases')
    op.create_index(op.f('ix_recovery_cases_payment_id'), 'recovery_cases', ['payment_id'], unique=False)
    # ### end Alembic commands ###
